package com.codingshuttle.razorpay.vault.entity;

import jakarta.persistence.*;

import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "vault_card")
public class VaultCard {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;// id of the card we are storing

    @Column(length = 4, nullable = false)
    private  String lastFour; // last four digits of the card

    @Column(length = 6, nullable = false)
    private  String bin; // first 6 digits of the branch like visa or mastercard

    @Column(nullable = false)
    private  byte[] encryptedPan;

    @Column(nullable = false)
    private  byte[] encryptedDek; // This is the secret to encrypt the PAN it will be generated by randomizer

    @Column(nullable = false)
    private  String brand;

    @Column(nullable = false)
    private String expiryMonth;

    @Column(nullable = false)
    private  String expiryYear;

    @Column (nullable = false)
    private String cardHolderName;

    private LocalDateTime deletedAt;
}
